Repository py-econometrics/pyfixest, pull requests merged in 2024-06, with the labels that each got.

#504 infrastructure: fix minor release drafter bugs
  .github/release-config.yml
Labels: infrastructure

#506 Fix bug in wildboottest method
  .coverage
  pyfixest/estimation/feols_.py
  pyfixest/estimation/multcomp.py
  tests/test_errors.py
  tests/test_multcomp.py
  tests/test_wildboottest.py
Labels: bug

#507 Docs: Poetry contributing
  docs/contributing.qmd
Labels: docs

#508 fix doubleml test bug
  tests/test_confint.py
Labels: dependencies

#510 VCOV: Refactoring of the VCOV Method
  .coverage
  pyfixest/estimation/feols_.py
  pyfixest/estimation/vcov_utils.py
Labels: maintenance

#511 update readme files
  README.md
  docs/pyfixest.md
Labels: docs

#512 type hints for vcov_utils
  .coverage
  pyfixest/estimation/feols_.py
  pyfixest/estimation/vcov_utils.py
Labels: maintenance

#520 Fix Contributing document format issue
  docs/contributing.qmd
Labels: docs
